name: backstage
description: "Live in-app logger for production. Hidden gesture + passcode"
version: 0.0.3
repository: https://github.com/serwidlick/backstage
issue_tracker: https://github.com/serwidlick/backstage/issues/
homepage: https://github.com/serwidlick/backstage

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  
  # Network logging and HTTP interception
  dio: ^5.4.0
  http: ^1.2.0
  
  # File operations and export
  path_provider: ^2.1.2
  csv: ^6.0.0
  archive: ^3.4.10
  
  # Platform sharing
  share_plus: ^7.2.2
  
  # Screenshots and image capture
  screenshot: ^2.3.0
  
  # Performance monitoring
  device_info_plus: ^10.1.0
  battery_plus: ^6.0.1
  
  # Platform-specific features
  sensors_plus: ^4.0.2
  local_auth: ^2.1.8
  
  # Charts and visualization
  fl_chart: ^0.66.2
  
  # Advanced data structures
  sqflite: ^2.3.2
  
  # Network and remote logging
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
