name: backstage
description: "Complete in-app debugging console with advanced logging, network monitoring, performance metrics, and export capabilities. Production-ready with security features."
version: 0.0.5
repository: https://github.com/serwidlick/backstage
issue_tracker: https://github.com/serwidlick/backstage/issues/
homepage: https://github.com/serwidlick/backstage

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  shared_preferences: ^2.5.3
  
  # Network logging and HTTP interception
  dio: ^5.9.0
  
  # File operations and export
  path_provider: ^2.1.5
  csv: ^6.0.0
  archive: ^4.0.7
  
  # Platform sharing
  share_plus: ^11.1.0
  
  # Performance monitoring
  battery_plus: ^6.2.3
  
  # Platform-specific features
  local_auth: ^2.3.0
  
  # Advanced data structures
  sqflite: ^2.4.2
  
  # Network and remote logging
  connectivity_plus: ^6.1.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
